version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:14.16

orbs:
  codecov: codecov/codecov@1.1.3

jobs:
  test-with-coverage-collection:
    executor: node
    steps:
      - checkout
      - run: npm ci
      - run: npm run test:coverage
      - codecov/upload
      - store_artifacts:
          path: coverage

workflows:
  test:
    jobs:
      - test-with-coverage-collection

